-- MySQL Script generated by MySQL Workbench
-- Wed Aug 11 21:46:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`usuario_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario_s` (
  `usuId` INT NOT NULL AUTO_INCREMENT,
  `usuLogin` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usuPassword` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usuUsuSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `usuEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `usuRemember_token` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usu_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuId`),
  UNIQUE INDEX `uniq_login` (`usuLogin` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`persona` (
  `perId` INT NOT NULL,
  `perDocumento` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Nos muestra el documento de la persona',
  `perNombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Nos muestra el nombre de la persona',
  `perApellido` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Nos muestra el apellido de la persona',
  `perEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `perUsuSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `per_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `per_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_s_usuId` INT NOT NULL,
  PRIMARY KEY (`perId`, `usuario_s_usuId`),
  UNIQUE INDEX `uniq_documento` (`perDocumento` ASC) ,
  INDEX `fk_persona_usuario_s1_idx` (`usuario_s_usuId` ASC) ,
  CONSTRAINT `fk_persona_usuario_s1`
    FOREIGN KEY (`usuario_s_usuId`)
    REFERENCES `proyecto`.`usuario_s` (`usuId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`cocinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cocinero` (
  `cocId` INT NOT NULL,
  `cocIdCocinero` INT NOT NULL,
  `cocIdCodigoCocinero` INT NOT NULL,
  `cocEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `cocSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cocCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cocUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`cocId`),
  INDEX `cocIdCocinero` (`cocIdCocinero` ASC) ,
  CONSTRAINT `cocinero_ibfk_1`
    FOREIGN KEY (`cocIdCocinero`)
    REFERENCES `proyecto`.`persona` (`perId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`tipo_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`tipo_plato` (
  `tipPlaId` INT NOT NULL,
  `tipPlaPlato` VARCHAR(100) NOT NULL,
  `tipPlaAdicional` VARCHAR(50) NULL DEFAULT NULL,
  `tipPlaBebida` VARCHAR(20) NOT NULL,
  `tipPlaPostre` VARCHAR(20) NULL DEFAULT NULL,
  `tipPlaEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `tipPlaSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `tipPlacreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tipPlaupdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tipPlaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`plato` (
  `plaId` INT NOT NULL,
  `plaIdTipoPlato` INT NOT NULL,
  `plaDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `plaPrecio` INT NOT NULL,
  `plaEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `plaSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `placreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `plaupdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`plaId`),
  INDEX `plaIdTipoPlato` (`plaIdTipoPlato` ASC) ,
  CONSTRAINT `plato_ibfk_1`
    FOREIGN KEY (`plaIdTipoPlato`)
    REFERENCES `proyecto`.`tipo_plato` (`tipPlaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`menu` (
  `menId` INT NOT NULL,
  `menIdPlato` INT NOT NULL,
  `menObservacion` VARCHAR(200) NULL DEFAULT NULL,
  `menEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `menSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `menCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `menUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`menId`),
  INDEX `menIdPlato` (`menIdPlato` ASC) ,
  CONSTRAINT `menu_ibfk_1`
    FOREIGN KEY (`menIdPlato`)
    REFERENCES `proyecto`.`plato` (`plaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`mesa` (
  `mesId` INT NOT NULL,
  `mesNumeroMesa` INT NOT NULL,
  `mesCantidadComensales` INT NOT NULL,
  `mesEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `mesSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `mesCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `mesUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`mesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`orden` (
  `ordId` INT NOT NULL,
  `ordIdMenu` INT NOT NULL,
  `ordIdMesa` INT NOT NULL,
  `ordvalorTotal` INT NOT NULL,
  `ordEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `ordSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ordCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ordUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ordId`),
  INDEX `ordIdMenu` (`ordIdMenu` ASC) ,
  INDEX `ordIdMesa` (`ordIdMesa` ASC) ,
  CONSTRAINT `orden_ibfk_1`
    FOREIGN KEY (`ordIdMenu`)
    REFERENCES `proyecto`.`menu` (`menId`),
  CONSTRAINT `orden_ibfk_2`
    FOREIGN KEY (`ordIdMesa`)
    REFERENCES `proyecto`.`mesa` (`mesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cocina` (
  `cociId` INT NOT NULL,
  `cociIdCocinero` INT NOT NULL,
  `cociIdOrden` INT NOT NULL,
  `cociEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `cociSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cociCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cociUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`cociId`),
  INDEX `cociIdCocinero` (`cociIdCocinero` ASC) ,
  INDEX `cociIdOrden` (`cociIdOrden` ASC) ,
  CONSTRAINT `cocina_ibfk_1`
    FOREIGN KEY (`cociIdCocinero`)
    REFERENCES `proyecto`.`cocinero` (`cocId`),
  CONSTRAINT `cocina_ibfk_2`
    FOREIGN KEY (`cociIdOrden`)
    REFERENCES `proyecto`.`orden` (`ordId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`codigo_mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`codigo_mesero` (
  `codMesId` INT NOT NULL,
  `codMesIdMesero` INT NOT NULL,
  `codMesCodigoMesero` INT NOT NULL,
  `codMesEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `codMesSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `codMescreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codMesupdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`codMesId`),
  UNIQUE INDEX `uk_cod_mese` (`codMesCodigoMesero` ASC) ,
  INDEX `codMesIdMesero` (`codMesIdMesero` ASC) ,
  CONSTRAINT `codigo_mesero_ibfk_1`
    FOREIGN KEY (`codMesIdMesero`)
    REFERENCES `proyecto`.`persona` (`perId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`factura` (
  `facId` INT NOT NULL,
  `facIdOrden` INT NOT NULL,
  `facIdCodigoMesero` INT NOT NULL,
  `facNombreCliente` VARCHAR(50) NULL DEFAULT NULL,
  `facEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `facSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `facCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `facUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`facId`),
  INDEX `facIdOrden` (`facIdOrden` ASC) ,
  INDEX `facIdCodigoMesero` (`facIdCodigoMesero` ASC) ,
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`facIdOrden`)
    REFERENCES `proyecto`.`orden` (`ordId`),
  CONSTRAINT `factura_ibfk_2`
    FOREIGN KEY (`facIdCodigoMesero`)
    REFERENCES `proyecto`.`codigo_mesero` (`codMesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`horario` (
  `horId` INT NOT NULL,
  `horIdCodigoMesero` INT NOT NULL,
  `horHoraInicio` TIME NOT NULL,
  `horHoraFin` TIME NOT NULL,
  `horFecha` DATE NOT NULL,
  `horObservacion` VARCHAR(1000) NULL DEFAULT NULL,
  `horEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `horSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `horcreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `horupdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`horId`),
  INDEX `horIdCodigoMesero` (`horIdCodigoMesero` ASC) ,
  CONSTRAINT `horario_ibfk_1`
    FOREIGN KEY (`horIdCodigoMesero`)
    REFERENCES `proyecto`.`codigo_mesero` (`codMesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`horario_cocinero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`horario_cocinero` (
  `horCocId` INT NOT NULL,
  `horCocIdCocinero` INT NOT NULL,
  `horCocHoraInicio` TIME NOT NULL,
  `horCocHoraFin` TIME NOT NULL,
  `horCocFecha` DATE NOT NULL,
  `horCocEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `horCocSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `horCocCreated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `horCocUpdated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`horCocId`),
  INDEX `horCocIdCocinero` (`horCocIdCocinero` ASC) ,
  CONSTRAINT `horario_cocinero_ibfk_1`
    FOREIGN KEY (`horCocIdCocinero`)
    REFERENCES `proyecto`.`cocinero` (`cocId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`rol` (
  `rolId` INT NOT NULL AUTO_INCREMENT,
  `rolNombre` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rolDescripcion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rolEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `rolUsuSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rol_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rol_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`rolId`),
  UNIQUE INDEX `uniq_nombrerol` (`rolNombre` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`usuario_s_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario_s_roles` (
  `id_usuario_s` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `fechaUserRol` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `usuRolUsuSesion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario_s`, `id_rol`),
  INDEX `usuario_s_roles_fk_rolidrol` (`id_rol` ASC) ,
  CONSTRAINT `usuario_s_roles_fk_rolidrol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `proyecto`.`rol` (`rolId`),
  CONSTRAINT `usuario_s_roles_fk_usuario_sid`
    FOREIGN KEY (`id_usuario_s`)
    REFERENCES `proyecto`.`usuario_s` (`usuId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
